
** About
# Network simulation that was developed during my PhD. 
Network simulation using Brian 2 and Pypet written to analyse the survivability of transient synapses of cortical neurons.

** Requirements
To run the network simulation a Python 3 environment with Brian 2, and Pypet is required. Git also has to be installed.

Any recent version of [[https://github.com/brian-team/brian2][Brian 2]] should work. However, to run very long simulations a fix discussed in [[https://github.com/brian-team/brian2/pull/1057][#1057]] is required.

Below is an example installation routine for setting up a virtualenv (tested on Ubuntu 16.04 only).

#+BEGIN_SRC sh
#!/bin/sh

virtualenv -p python3 /home/$USER/env/synsrv
source /home/$USER/env/synsrv/bin/activate

# Brian 2 branch that fixes bug for long simulations
pip install -e git+https://github.com/brian-team/brian2@355cbf98061f2ae4c4afdc1600f363c5d8c0979d#egg=Brian2

pip install mrestimator==0.1.5
pip install elephant==0.6.0

pip install tables==3.5.1
pip install pypet==0.4.3

pip install GitPython
#+END_SRC


** Installation

Get the code from this repository including submodules with

: git clone  --recurse-submodules https://github.com/synsrv/src_net



** Run a simulation
To verify your installation, within ~src_net~ run

#+BEGIN_SRC sh
./run_test.sh -l tests/net_tests/test_standard_net/
#+END_SRC

This will create a directory ~tests/~ on the same level as ~src_net~ where the code is copied an executed.

** Explore parameters

To run simulations exploring different parameter sets, create an ~explored_params.py~ in ~src_net/net/~, as for example found in any of the tests in ~net_tests/~. In the ~input_dict~ of ~explored_params.py~ specify the parameter setting of your choice and the runn simulation via

#+BEGIN_SRC 
./run.sh -l -n 2 -P "_two-concurrent-sims" -E
#+END_SRC

This will create ~running/~ and ~completed/~ directories on the same level as ~src_net/~. Once finished, the simulation directory is moved from ~running/~ to ~completed/~.




